import{a as E,S as P,i as a}from"./assets/vendor-D_DhjhBq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function u(o,t){const s="51879561-dd43d0ef22fd8f83e88d07dfd",n="https://pixabay.com/api/",e=new URLSearchParams({key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15});return(await E.get(`${n}?${e}`)).data}const p=document.querySelector(".gallery"),g=document.querySelector(".loader"),f=document.querySelector(".load-more-btn"),q=new P(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:c,comments:S,downloads:v})=>`
    <li class="gallery-item">
      <a href="${n}">
        <img src="${s}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes</b><span>${r}</span></p>
        <p><b>Views</b><span>${c}</span></p>
        <p><b>Comments</b><span>${S}</span></p>
        <p><b>Downloads</b><span>${v}</span></p>
      </div>
    </li>
  `).join("");p.insertAdjacentHTML("beforeend",t),q.refresh()}function $(){p.innerHTML=""}function m(){g.classList.remove("is-hidden")}function y(){g.classList.add("is-hidden")}function b(){f.classList.remove("is-hidden")}function L(){f.classList.add("is-hidden")}let l="",i=1;const w=15,d=document.querySelector(".form"),M=document.querySelector(".load-more-btn");d.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.target.elements.query.value.trim(),!l){a.warning({title:"Warning",message:"The search field cannot be empty!",position:"topRight"});return}i=1,$(),L(),m();try{const t=await u(l,i);if(t.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(t.hits);const s=Math.ceil(t.totalHits/w);i<s?b():a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){console.error("Error fetching images:",t),a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y(),d.reset()}});M.addEventListener("click",async()=>{i+=1,L(),m();try{const o=await u(l,i);h(o.hits);const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"});const s=Math.ceil(o.totalHits/w);i<s?b():a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(o){console.error("Error fetching images:",o),a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}});
//# sourceMappingURL=index.js.map
